### ISSUE TITLE
奇妙な記述

### ISSUE THREAD

**Issue by arton** [karino2/AndroidSupportTech#1]
P.153本文下から5行目
「このint値の上位2bitに、（略）付加情報など、いろいろな数値を埋め込むことになっています。この付加情報のうち、上位の2bitには（略）」
最初の文では上位2ビット⊃付加情報 と読めますが、次の文では 付加情報 ⊃ 上位2bitになっています。
MODEが3種類なので、あと1種類あるとしても、相当違和感がありました。

**Comment by karino2** [comment]
本当だ。「上位8bitに（略）なっています。この付加情報のうち上位2bitには～」が正解ですね。

訂正をissue trackerで集めるのは、荒れなければ良いかも。
訂正情報を作ったらcloseします。
ご報告どうもありがとうございます。

**Comment by fujii** [comment]
ソースはこれでしょうか？
https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/view/View.java#22342
上位8bit使っているように見えないですが？

**Comment by karino2** [comment]
うーむ、確かに微妙な所がありますね。
onMeasure()の呼び出しの上で、8bitにtoo smallとかを詰めるのですが、そこがうまく本文では記述出来ていないかも。
とりあえず以下を見ていただくと分かりますが、

https://github.com/android/platform_frameworks_base/blob/android-cts-7.0_r6/core/java/android/view/View.java#L19889

このMEASURED_STATE_MASKが今言っている上位8bitうんぬん、という奴です。
記述はちょっと気を付けて直します。

＃としれっとコメントしているおぬしはふじひろだな？お久しぶりです。読んでくれましたか。

**Comment by fujii** [comment]
なるほど。
\# はい、お久しぶりです。拝読しております。横から失礼いたしました。

**Comment by karino2** [comment]
正誤表に反映しました。ご報告ありがとうございました。

https://github.com/karino2/AndroidSupportTech/blob/master/Part1/Errata.md
